//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RANKSOnlineWholesale.DBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardInfo
    {
        public int CardInfoId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CardNumber { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
