//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RANKSOnlineWholesale.DBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int DeliveryId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine { get; set; }
        public string Parish { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string PaymentType { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
